language: node_js
sudo: false
node_js:
- node
before_install:
- chmod +x travis-renameRef.sh
install:
- npm install
script:
- echo "Bump version and flyway migrate db"
- if [ "$TRAVIS_BRANCH" == "testChangesTravis" ]; then ./travis-renameRef.sh; fi
env:
  global:
    secure: v2ISeZUm5T//H1YqjTNOrpi21k7xoPHFIet4tU8qefushadav4WVMPgEPl6SKtfO1tTf/W032WCyh14YUtJSH7bofKaqCE7nwXZo/vqxhP7EERo1yWKQnhHgUu71CgZjOADN4KBGA6wrSaKqN1miZQ0i2G5hducZR+vQNlWC3c/IT/xKUl5gYMLYuvARxg1Tl/YzaDTo8xSEAwBX52a4MR5xqAx8rbWury8ld6/WSTuTvLrVCPK/EVff+PLE53raE5aMiJUa9/HIfj/jsxDFtNgntXtnnwKulyQNvgmrkjeNyD5CEfaq8ATGx5xxF149Le0el8pmBgAQQ06ELMXSnbQax+9m3ycIgx07rwODHwL5/X8yX7U4hy0Tl23z/0oxOvbk5MyLXzUnqlkUwQkZ9dPHRA6x7+yZ4KgUYDQsWcQank49731QDwtAgWU3qIgM22jIaRD6Qjp7ZhiQtpP/fdghm7yjCVwULwBEbGBqdA5rX8Jp5hCEuR0aBIoW5Pk/NZxvtMsDFuWimznBMX7BWTjXxFoTdLrYMu0UzMDDve7N+vPRrSkAf4mzyq+yQfaX+TSEmboQRkeftnMN48J0nJ8qR6S9YMXqA432tSuH95lLzFYOOgUa9m/0dOWUujdQeLxKrUPj7UCcdR5Z474iWSt746Y8S2q0dIEsebrQH0g=
