language: node_js
sudo: false
node_js:
  - "node"
install:
  - npm install
script:
  - echo "Bump version and flyway migrate db"
  - if [ "$TRAVIS_BRANCH" == "testChangesTravis" ]; then ./travis-renameRef.sh; fi
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - npm test
  