language: node_js
sudo: false
node_js:
  - "node"
install:
  - npm install
script:
  - if [CHANGES=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master))]; then
    npm test
    fi