language: node_js
sudo: false
node_js:
  - "node"
install:
  - npm install
script:
  - echo "Bump version and flyway migrate db"
  - if [ $TRAVIS_BRANCH == "testChangesTravis" ]; then node validator/master/renameRef.js; fi
  - npm test
  