language: node_js
sudo: false
node_js:
- node
before_install:
- chmod +x travis-renameRef.sh
install:
- npm install
script:
- echo "Bump version and flyway migrate db"
- if [ "$TRAVIS_BRANCH" == "testChangesTravis" ]; then ./travis-renameRef.sh; fi
env:
  global:
    secure: 50MlXLEpFSUy3y74QjJZWHwLnC7ZLTjaQ3EhEcsWuPo5V1ggxlBpTd4B08DSGsi4MLO6kta2Ly2EB23oUgEc8zJPB8ptbL/ObA7+/yh5FgdrhjsjnilNGRg2c8dlL5eMFIiJkQQ2VRG5tcJ8wYNqVroJahML2gZKoF8vQ2dRiAn8wdBpcGMZfEr6hWsdAwdAqyX4BOUT1tNOC1lGPCghRtpo8N4tGouAG5yK4O7Pe1IxdcdAVjiNb/bFVjht4l1YRiUjohHwgv73kO3iUnwL5Rt+GLXkWikhu06ynJR5Ws71unWgKOBZ8UzIEs1A7FFqySYvQy6WireGU9GltTPo1OIiKf4gK8j8fvs72itaYqt/F3ZsViE2q8FkJzIsCJaXGEHZLAcTom3Uu8lxAq1+JN6z6ddN9BJgyc3DiGZ2LQcgf3IgEW55yeBt5bbS0v+ACJX1N9WzUCYRH3wrn2IFln9DpEFgYix7oVa3Qd4eGboMZH6P5iexw2Y3/SiF9haOPJHkHMROeiIb+BPDbxAAYmLOWDKfZeyTCbZCT7ZiBp4gd1CQeUVmQxXpQIbrwlZ1t5MtVvDZc/ZqNcD8BeGg6Lx/3c+qvm/dpOs5XpieQokrPYdhwH+m8Mp3cCoLrmoIMKmYRfphrUjnh31BBfwvK2QVRZQ+Su3uSHXlYFGaf34=
